version: "3"

# Refer to this example, make necessary changes and rename this file to docker-compose.yml

services:

  gRPC: 
    image: valorad/hyena-grpc
    container_name: hyena-grpc
    expose:
      - 50051
    volumes:
      - "/path/2/gRPC/configs:/www/hyenaGRPC/configs"
      - "/path/2/gRPC/statics:/www/hyenaGRPC/statics"
    networks:
      hyena_net:
        ipv4_address: 172.22.0.100

  proxy: 
    image: valorad/hyena-proxy
    container_name: hyena-proxy
    expose:
      - 3000
    volumes:
      - "/path/2/proxy/configs:/www/hyenaProxy/configs"
    networks:
      hyena_net:
        ipv4_address: 172.22.0.101
  
networks:

  hyena_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
