# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ruby

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "Gemfile.lock" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install apiaryio
            apiary publish --api-name="hyenaproxy" --path="server-proxy/src/router/api.apib"

      # - save_cache:
      #     paths:
      #       - ./vendor/bundle
      #     key: v1-dependencies-{{ checksum "Gemfile.lock" }}
