FORMAT: 1A
HOST: http://localhost:3000/

# hyena-workload-provider:proxy

Polls is a simple API allowing consumers to view polls and vote in them.

## Category Route [/api/workload/category/{category}{?query}]

### Get workload batches by category [GET]

+ Response 200 (application/json)

        [
            {
                "message": "Fxck you Apiary!!!"
            }
        ]
